### ISSUE TITLE
并不需要 android.permission.MOUNT_UNMOUNT_FILESYSTEMS 这个权限

### ISSUE THREAD

**Issue by TakWolf** [YancyYe/ImageSelector#1]
[http://developer.android.com/intl/zh-cn/reference/android/Manifest.permission.html](http://developer.android.com/intl/zh-cn/reference/android/Manifest.permission.html)

![image](https://cloud.githubusercontent.com/assets/6064962/11584624/4407af10-9aa0-11e5-91ff-470f7dbec4f1.png)

Allows mounting and unmounting file systems for removable storage.
允许挂载和卸载文件系统。

Not for use by third-party applications.
不提供第三方应用使用。

只要有扩展的读写权限就可以了

**Comment by YancyYe** [comment]
好的  谢谢反馈。   我会持续更新  完善的、  接下来我会 完善 图片加载系统。  让使用者可以自定义 选择使用第三方的 图片加载工具

**Comment by YancyYe** [comment]
已完善
