### ISSUE TITLE
在部分安卓6.01的机器上闪退问题

### ISSUE THREAD

**Issue by morosek** [YancyYe/ImageSelector#20]
目前测试中，在小米5的miui8，安卓版本6.01系统下，在进入选择图片模式，如果直接点击图片而不是右上角的checkbox，选择图片页面会闪退，导致app进入假死状态，同样的问题也在三星s7安卓6.01系统上，希望作者能给予答复！不尽感激！

**Comment by YancyYe** [comment]
https://github.com/YancyYe/GalleryPick  项目已重构
