### ISSUE TITLE
permission error in android 6.0

### ISSUE THREAD

**Issue by AndwareSsj** [YancyYe/ImageSelector#4]
build library in:
ANDROID_BUILD_TARGET_SDK_VERSION=23
ANDROID_BUILD_TOOLS_VERSION=23.0.1
ANDROID_BUILD_SDK_VERSION=23

**Comment by YancyYe** [comment]
我这边测试没问题    你能不能在测一测

**Comment by fishyer** [comment]
6.0的时候需要运行时验证权限,ImageSelectorActivity需要修改一下，否则会报错：

 java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera/.Camera clip={text/uri-list U:file:///storage/emulated/0/ImageSelector/Pictures/20160516160155.jpg} (has extras) } from ProcessRecord{c2f8bde 23322:com.che.carcheck/u0a128} (pid=23322, uid=10128) with revoked permission android.permission.CAMERA

**Comment by AndwareSsj** [comment]
@fishyer best way to use permissionsdispatcher

**Comment by gaohailong** [comment]
设置为9张图片时候，再点击拍照，又会多出现一张图片，这样就不会控制在9张图片之内。这是个bug

**Comment by YancyYe** [comment]
https://github.com/YancyYe/GalleryPick  项目已重构
