### ISSUE TITLE
Error : endless add All Images

### ISSUE THREAD

**Issue by DenisYKa** [YancyYe/ImageSelector#9]
请点击照片的文件夹，整个文件夹和重叠的照片总数

endless add All Images and endless add same folder...

I guess the cause of this problem is 

new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        folderPopupWindow.dismiss();
                        if (index == 0) {
                            getActivity().getSupportLoaderManager().initLoader(LOADER_ALL, null, mLoaderCallback);

How to fix it ?? please help me :)

**Comment by YancyYe** [comment]
https://github.com/YancyYe/GalleryPick  项目已重构
